# Site Configuration
titleBase: Documentação.dev
favicon: favicon.ico

# Social media links
social:
  - name: Github
    url: https://github.com/ulisseshen/documentacao.dev
  - name: LinkedIn
    url: https://www.linkedin.com/in/ulisseshen/